### ISSUE TITLE
JS - callEpcApi function working

### ISSUE THREAD

**Issue by chelsea314** [eco-watch/ecolookuptool#3]

**Comment by neverekt** [comment]
Demo created using AJAX instead of fetch and pushed to branch jt/javascript - the demo will console log JSON response from the API given the address and postcode arguments from the form input fields. Needs results to be filered so only the most recent dated result is returned in case of duplicates and also there are 93 values in the array, maybe around 10 of them are worth displaying.

**Comment by neverekt** [comment]
finally finished debugging
